language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t venkats1/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true venkats1/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "ap-south-1" 
  app: docker-react
  env: Dockerreact-env
  bucket_name:  "elasticbeanstalk-ap-south-1-158368706475"
  bucket_path:  "docker-react"
  on:
    branch: main
  access_key_id: $AccessKey
  secret_access_key:
    secure: "$key"