language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t venkats1/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true venkats1/docker-react npm run test